name: si_store
description: "A new Flutter project."


publish_to: 'none' 




version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


#************************** Packages **************************************
dependencies:
  flutter:
    sdk: flutter
  #Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.3.0
  libphonenumber: ^2.0.0
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0
  carousel_slider: ^4.2.1

  #firebase
  firebase_core: ^3.6.0



  #icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

  #State Management
  get: ^4.6.5
  get_storage: ^2.1.1


  #Product Specific
  lottie: ^3.1.2
  connectivity_plus: ^3.0.3
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4





#**************************./Packages End **************************************
dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_lints: ^3.0.0





flutter:

  
  
  
  uses-material-design: true

  #................... Local Assets ............................
  assets:
    - assets/logos/main_logo.png
    - assets/logos/main_logo2.png
    - assets/logos/BG.jpg
    - assets/icons/brands/
    - assets/icons/category/physical.png
    - assets/images/onboarding_images/
    - assets/images/verifyemail.png
    - assets/images/success.png
    - assets/images/resetmail.gif
    - assets/images/slider_product/
    - assets/images/grid_product/
    - assets/images/docerImage.jpg

#  #................... Local Assets ............................
