// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwy8xvU-nFOm0m_NAg3NV9v8e1fWvDorw',
    appId: '1:65011312977:web:a20662889d0e0680cecb70',
    messagingSenderId: '65011312977',
    projectId: 'si-cart',
    authDomain: 'si-cart.firebaseapp.com',
    storageBucket: 'si-cart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-c2lrWLOGnd-8S2jX1-yG8x2Q6EDVO8M',
    appId: '1:65011312977:android:1e95b7b888d12716cecb70',
    messagingSenderId: '65011312977',
    projectId: 'si-cart',
    storageBucket: 'si-cart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJqkS9Ky1yrN6RxjDLxwGNSsMxDYYPe3I',
    appId: '1:65011312977:ios:8a87176ae8668a50cecb70',
    messagingSenderId: '65011312977',
    projectId: 'si-cart',
    storageBucket: 'si-cart.appspot.com',
    androidClientId: '65011312977-l673ol3nnr2i2jkg7j787g3ivgfovgem.apps.googleusercontent.com',
    iosClientId: '65011312977-hvfomimj7298g1jbi926q93ptkj0luvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.siStore',
  );

}